# This rule is not used by the project kubebuilder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to pc.pc.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: crd-viewer-role
rules:
- apiGroups:
  - pc.pc.com
  resources:
  - crds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pc.pc.com
  resources:
  - crds/status
  verbs:
  - get
