---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pc.pc.com
  resources:
  - crds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pc.pc.com
  resources:
  - crds/finalizers
  verbs:
  - update
- apiGroups:
  - pc.pc.com
  resources:
  - crds/status
  verbs:
  - get
  - patch
  - update
